### PR TITLE
What is MEV and how does it work?

### PR DESCRIPTION
**Pull request by therevealer**

### CODE REVIEW

**Comment by therevealer** [comment]
@Genesis3800 I created the pull request... looking forward your feedback.

**Comment by Genesis3800** [comment]
Thank you for the PR @therevealer . 
I will go through it and get back to you for edits soon.

**Comment by therevealer** [comment]
> Thank you for the PR @therevealer . I will go through it and get back to you for edits soon.

Okay Expecting your reply

**Comment by Genesis3800** [comment]
Hey @therevealer ,
I reviewed your article and I really liked it. 
A bunch of grammatical and formatting edits need to be made, but we'll be doing that in-house. 

I don't have any significant edits that I require you to make. I'll be passing the article internally for a final plagiarism check. I like your article a lot and will hopefully be merging it soon.
Cheers! Great work.

**Comment by therevealer** [comment]
> 

Thanks... This means a lot too. Looking forward to writing more!

**Comment by Genesis3800** [comment]
Hey @therevealer ,
Thank you for your contribution to the developer hub.
We appreciate having you with us.
To move forward, please send me your email address.

I will reach out to you via mail to request your bank details for processing your payment.

**Comment by therevealer** [comment]
Hello Priyank,

It's really nice to be part of the contributors, I look forward to working
on more projects.
Here is the email address you requested.
 ***@***.***

**Comment by Genesis3800** [comment]
Hey @therevealer ,
image
This is what I see.
I think this is a Github issue. Please send me the email with words separated by spaces.

Example-
"myname @ gmail . com"

**Comment by therevealer** [comment]
Okay,Here you go.therevealerdev @ gmail .comOn 5 Jan 2023, at 2:47 PM, Priyank Gupta ***@***.***> wrote:﻿
Hey @therevealer ,

This is what I see.
I think this is a Github issue. Please send me the email with words separated by spaces.
Example-
"myname @ gmail . com"

**Pull request merged**
